### PR TITLE
correctly identify toolchain specified with `--toolchain`

### PR DESCRIPTION
**Pull request by Emilgardis**

### CODE REVIEW

**Review by Enselic — APPROVED** [review]
Would be nice with a regression test  for this (that fails without the fix), but I've nagged enough about tests before, so I'll let it slip this time. Maybe you'll add tests in another PR :)

(From now on whenever I approve a PR you are free to merge it when you see fit)

**Comment by Emilgardis** [comment]
I agree with adding a test for this, this one feels better to add one for, and it could be a regular test, only need to add another invocation here https://github.com/Enselic/cargo-public-api/blob/a4945abbc58f0f6edbdabf0a928ab67cef0052f4/scripts/test-invocation-variants.sh#L89 that uses `--toolchain`

**Comment by Emilgardis** [comment]
https://github.com/Enselic/cargo-public-api/runs/8171051195?check_suite_focus=true and the regression test works

**Review by Enselic — APPROVED** [review]
Great, thank you!

**Pull request merged**
