### PR TITLE
Support `nightly-2024-10-13` and later

### LINKED ISSUE #631: Update needed since nightly 2024-10-13
Upstream: https://github.com/rust-lang/rust/pull/130078

See: https://github.com/aya-rs/aya/actions/runs/11311392733/job/31457575922

### PR DESCRIPTION
**Pull request by Enselic**
Closes #631

### CODE REVIEW

**Review by tamird — APPROVED** [review]
Pretty straightforward.

**Review by robjtede — APPROVED** [review]

**Comment by tamird** [comment]
Could you ping this when a new release has been cut?

**Comment by Enselic** [comment]
Sure. Well, I already released it: https://github.com/cargo-public-api/cargo-public-api/releases/tag/v0.39.0

**Comment by tamird** [comment]
Ah, one minute after I posted that. Thanks!

**Pull request merged**
