### PR TITLE
Bump rustdoc-json to v0.9.3

### PR DESCRIPTION
**Pull request by Billy99**
Changes to rustdoc-types required updates to repo.

### CODE REVIEW

**Comment by Enselic** [comment]
Edit: Oops, this comment was supposed to go to the other PR. I moved it there.

**Comment by Enselic** [comment]
I think we can skip this and update the public-api crate directly, to avoid churn for downstream users? In other words, I don't think there are any technical reasons to make a new release of this package? But please correct me if I'm wrong.

Also see my comment on the other PR.

**Comment by Billy99** [comment]
Running the command `tag=$(git tag --sort=-creatordate | grep ^rustdoc-json-v | head -n1) ; git diff $tag -- rustdoc-json/`, I saw changes so thought it was needed. However, after relooking , the only change I can identify is in `rustdoc-json/examples/build-rustdoc-json.rs` and was needed to run `./scripts/run-ci-locally.sh`:

```
$ ./scripts/run-ci-locally.sh 
+ export CARGO_TERM_COLOR=always
+ CARGO_TERM_COLOR=always
+ cargo fmt -- --check
+ RUSTDOCFLAGS='--deny warnings'
+ cargo doc --locked --no-deps --document-private-items
 Documenting public-api v0.37.0 (/home/bmcfall/src/cargo-public-api/public-api)
 Documenting rustup-toolchain v0.1.7 (/home/bmcfall/src/cargo-public-api/rustup-toolchain)
 Documenting rustdoc-json v0.9.2 (/home/bmcfall/src/cargo-public-api/rustdoc-json)
 Documenting cargo-public-api v0.37.0 (/home/bmcfall/src/cargo-public-api/cargo-public-api)
    Finished `dev` profile [unoptimized + debuginfo] target(s) in 1.16s
   Generated /home/bmcfall/src/cargo-public-api/target/doc/cargo_public_api/index.html and 4 other files
+ scripts/cargo-clippy.sh
    Checking rustup-toolchain v0.1.7 (/home/bmcfall/src/cargo-public-api/rustup-toolchain)
    Checking rustdoc-json v0.9.2 (/home/bmcfall/src/cargo-public-api/rustdoc-json)
error: the borrowed expression implements the required traits
  --> rustdoc-json/examples/build-rustdoc-json.rs:23:13
   |
23 |     cmd.arg(&format!("cat {path:?} | python3 -m json.tool | less"));
   |             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ help: change this to: `format!("cat {path:?} | python3 -m json.tool | less")`
   |
   = help: for further information visit https://rust-lang.github.io/rust-clippy/master/index.html#needless_borrows_for_generic_args
   = note: `-D clippy::needless-borrows-for-generic-args` implied by `-D clippy::all`
   = help: to override `-D clippy::all` add `#[allow(clippy::needless_borrows_for_generic_args)]`

error: could not compile `rustdoc-json` (example "build-rustdoc-json") due to 1 previous error
warning: build failed, waiting for other jobs to finish...
```

https://github.com/cargo-public-api/cargo-public-api/commit/d768efa342be6ab0d1759b17f2718c59c1be4a0f#diff-e71c375b9a8c6919df1c519dc1a38d51021edace7854d311ed26e010ba19acf4R23

**Comment by Billy99** [comment]
Sorry, one other change, but don't know if it's considered breaking or not:
```
diff --git a/rustdoc-json/tests/public-api.txt b/rustdoc-json/tests/public-api.txt
index ca812d1..97d274d 100644
--- a/rustdoc-json/tests/public-api.txt
+++ b/rustdoc-json/tests/public-api.txt
@@ -81,8 +81,6 @@ impl<T> core::borrow::BorrowMut<T> for rustdoc_json::Color where T: core::marker
 pub fn rustdoc_json::Color::borrow_mut(&mut self) -> &mut T
 impl<T> core::clone::CloneToUninit for rustdoc_json::Color where T: core::clone::Clone
 pub unsafe fn rustdoc_json::Color::clone_to_uninit(&self, dst: *mut T)
-impl<T> core::clone::CloneToUninit for rustdoc_json::Color where T: core::marker::Copy
-pub unsafe fn rustdoc_json::Color::clone_to_uninit(&self, dst: *mut T)
 impl<T> core::convert::From<T> for rustdoc_json::Color
 pub fn rustdoc_json::Color::from(t: T) -> T
 impl<T> tracing::instrument::Instrument for rustdoc_json::Color
```

**Comment by Enselic** [comment]
Since as far as I can tell neither of these changes affects users of the library, I think we can skip this one.

**Comment by Billy99** [comment]
Agree, thanks.

**Pull request closed without merging**
