### PR TITLE
Support for `--package workspace-package` (or short form `-p`)

### LINKED ISSUE #82: Allow using `-p` to select package in workspace
If you stand in the root of this git repo, you can run this command to build the HTML docs of say the `rustdoc-json` crate:

```bash
cargo doc -p rustdoc-json
```

It would be convenient to be able to use the same flag for `cargo public-api`, like this:
```bash
cargo public-api -p rustdoc-json
```

because currently you have to use the much longer:

```bash
cargo public-api  --manifest-path rustdoc-json/Cargo.toml
```

which means you can barely re-use the `cargo doc` command from your shell history. It is worth noting that `cargo doc` also support the longer form that we currently use:

```
cargo doc --manifest-path rustdoc-json/Cargo.toml
```

Type `cargo help doc` and read the **Package Selection** section for more info on how package selection works with `cargo doc`.

### PR DESCRIPTION
**Pull request by Emilgardis**
depends on #115

resolves #82

### CODE REVIEW

**Review by Enselic — APPROVED** [review]
Stellar job 🌟 

I have reviewed the diff between this and your `features` branch, and this looks ready to merge to me. It has a test and everything. Nice fixup of the handling of temporary files btw.

But we must of course wait to merge this until the other PR has been merged first.

**Comment by Emilgardis** [comment]
pro tip for you

image


gives a diff of specific commit in pr :)

**Comment by Enselic** [comment]
Cool, thanks for the tip! How did you know I didn't know? 😀 (Because I said " have reviewed the diff between this and your features branch" probably :) )

**Comment by Enselic** [comment]
I think we'll want to rebase this because right now the diff that GitHub shows looks odd?

**Comment by Enselic** [comment]
Thank you!

**Pull request merged**
