### PR TITLE
Update clap to v4

### PR DESCRIPTION
**Pull request by dnaka91**
Noticed that the project is still using clap v3, and tried updating it to v4. I hope I captured all the special configs right, some local tests all worked out fine.

### CODE REVIEW

**Comment by Enselic** [comment]
Looks great, thanks! Throughout the project I have been careful to ensure that there is a good set of regression tests in place. And since CI is green, I am confident nothing major broke 👍

**Comment by dnaka91** [comment]
Thank you for the quick merge! Saw the many tests, which are really great. Should do that degree of regression tests on my own projects :sweat_smile:.

If anything turns out to be broken later, just ping me, and I'll have a look.

**Comment by Enselic** [comment]
Thank you for the offer 🙏 

Do you happen to know how to make clap 4 wrap --help text paragraphs?

With clap 3 we had:

```
        --with-blanket-implementations
            Raise this flag to make items part of blanket implementations such as `impl<T> Any for
            T`, `impl<T> Borrow<T> for T`, and `impl<T, U> Into<U> for T where U: From<T>` be
            included in the list of public items of a crate.
```

With clap 4 we have:

```
      --with-blanket-implementations
          Raise this flag to make items part of blanket implementations such as `impl<T> Any for T`, `impl<T> Borrow<T> for T`, and `impl<T, U> Into<U> for T where U: From<T>` be included in the list of public items of a crate.
```

This is on Mac in Terminal.app when I do `cargo run -- --help`

**Comment by dnaka91** [comment]
Ah yes, that is now hidden behind a feature flag. Maybe was even before, but is now an opt-in feature. I'll create another PR to enable it 🙇‍♂️

**Pull request merged**
