### PR TITLE
Release v0.16.0

### PR DESCRIPTION
**Pull request by Emilgardis**

### CODE REVIEW

**Comment by Emilgardis** [comment]
it won't work very well to do this in one pr 😅

I understand the process but could you do it instead @Enselic :D

**Comment by Enselic** [comment]
Hmm why won't it work well?  I would love to see you make a release 🤩 

If the release checklist is unclear I should clarify it!

**Comment by Emilgardis** [comment]
Oh yeah, nvm... Forgot to bump the version dependency..

**Comment by Enselic** [comment]
Don't forget changing 

```
| v0.15.x          | nightly-2022-08-15 —                    |
```

to

```
| v0.16.x          | nightly-2022-08-15 —                    |
```

:) 

(hmm I should write a test for that)

**Comment by Emilgardis** [comment]
with that, how do I know what version 0.15.x supports?

**Comment by Enselic** [comment]
since we didn't bump `MINIMUM_RUSTDOC_JSON_VERSION` it is the same as before, so you literally should just change the `5` to `6`

**Comment by Emilgardis** [comment]
now I'm confused about the matrix again, changing that line suggests to me that versions 0.13.0 -> 0.15.0 supports rustdoc format from nightly-2022-08-10 —> nightly-2022-08-14

**Comment by Enselic** [comment]
Oooooh, I actually never thought about that it could be interpreted that way, but now that you mention it it indeed seems confusing. Hmm. So maybe do as you first proposed then? So like this then:

```
| cargo-public-api  | Understands the rustdoc JSON output of  |
| ----------------- | --------------------------------------- |
| v0.15.x - v0.16.x | nightly-2022-08-15 —                    |
| v0.13.x - v0.14.x | nightly-2022-08-10 — nightly-2022-08-14 |
| v0.12.x           | nightly-2022-05-19 — nightly-2022-08-09 |
| v0.10.x - v0.11.x | nightly-2022-03-14 — nightly-2022-05-18 |
| v0.5.x  - v0.9.x  | nightly-2022-02-23 — nightly-2022-03-13 |
| v0.2.x  - v0.3.x  | nightly-2022-01-19 — nightly-2022-02-22 |
| v0.0.5  - v0.1.x  | nightly-2021-10-11 — nightly-2022-01-18 |
```

it seems a bit too verbose for my taste, but maybe because I'm not used to it. I'm fine with having it that way until we come up with some better way, if we do.

**Comment by Emilgardis** [comment]
I think I prefer

```
| cargo-public-api | Understands the rustdoc JSON output of  |
| ---------------- | --------------------------------------- |
| v0.15.x          | nightly-2022-08-15 —                    |
| v0.13.x          | nightly-2022-08-10 — nightly-2022-08-14 |
| v0.12.x          | nightly-2022-05-19 — nightly-2022-08-09 |
| v0.10.x          | nightly-2022-03-14 — nightly-2022-05-18 |
| v0.5.x           | nightly-2022-02-23 — nightly-2022-03-13 |
| v0.2.x           | nightly-2022-01-19 — nightly-2022-02-22 |
| v0.0.5           | nightly-2021-10-11 — nightly-2022-01-18 |
```

but can do it your suggested way ofc if you prefer it

**Comment by Enselic** [comment]
I agree that version is better than what I have now on master, but now I'm kinda starting to like the version where you don't have to think so much :P. If we remove `v` I think it feels better:

```
| cargo-public-api | Understands the rustdoc JSON output of  |
| ---------------- | --------------------------------------- |
| 0.15.x - 0.16.x  | nightly-2022-08-15 —                    |
| 0.13.x - 0.14.x  | nightly-2022-08-10 — nightly-2022-08-14 |
| 0.12.x           | nightly-2022-05-19 — nightly-2022-08-09 |
| 0.10.x - 0.11.x  | nightly-2022-03-14 — nightly-2022-05-18 |
| 0.5.x  - 0.9.x   | nightly-2022-02-23 — nightly-2022-03-13 |
| 0.2.x  - 0.3.x   | nightly-2022-01-19 — nightly-2022-02-22 |
| 0.0.5  - 0.1.x   | nightly-2021-10-11 — nightly-2022-01-18 |
```

If you also think the above looks OK then I think we should go with that

**Review by Enselic — APPROVED** [review]
Looks good! So the only things left now are I think:
* Merge this
* Trigger release via GitHub Actions as instructed in the checklist

Good luck! 😀

**Comment by Emilgardis** [comment]
https://github.com/Enselic/cargo-public-api/actions/runs/2985692416 :)

**Comment by Enselic** [comment]
Oops, it failed, my fault 😅 

Let's see...

**Comment by Enselic** [comment]
Seems my test-utils hack messed things up

I think I need to re-think how test utils are structured, but I'm running out of time for the evening... sorry for sabotaging your first release :(

Hopefully I'll find the time tomorrow

**Comment by Emilgardis** [comment]
haha, no worries, it's a shame you can't share dev-deps like that. Simplest solution I can think of is 

```
#[path = "../../test_util.rs"]
mod test_util;
```

**Comment by Emilgardis** [comment]
probably want to do a 

```
git revert c67266da797dd190e5784b7b96b2b4be0e8d708a
```

and push that

**Comment by Enselic** [comment]
Congrats on the release 🥳

**Pull request merged**
